apiVersion: v1
kind: Secret
metadata:
  name: hf-token-param
type: Opaque
stringData:
  HF: 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-param5b
  namespace: vllm-models
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-param5b
  template:
    metadata:
      labels:
        app: model-param5b
    spec:
      tolerations:
        - key: nvidia.com/gpu
          value: 'True'
          effect: "NoSchedule"
      serviceAccountName: deployer
      containers:
        - name: vllm-model-param5b
          image: vllm/vllm-openai:v0.14.1
          env:
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token-param
                  key: HF
            - name: CUDA_VISIBLE_DEVICES
              value: "0"
            - name: VLLM_LOGGING_LEVEL
              value: INFO
            - name: HUGGINGFACE_HUB_CACHE
              value: "/platform_storage/HF_HOME"
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Starting Param model on CUDA:0"
              huggingface-cli login --token "$HUGGING_FACE_HUB_TOKEN"
              jq '.rope_scaling = {"type":"linear","factor":1.0}' \
              ~/.cache/huggingface/hub/models--bharatgenai--Param-1-5B/snapshots/d18442936c6b2f48dab3ff5d61d607d008fc4919/config.json \
              > /tmp/config.json && \
              mv /tmp/config.json \
              ~/.cache/huggingface/hub/models--bharatgenai--Param-1-5B/snapshots/d18442936c6b2f48dab3ff5d61d607d008fc4919/config.json
              vllm serve bharatgenai/Param-1-5B \
              --trust_remote_code \
              --revision vllm-compatible\
                --host 0.0.0.0 \
                --port 8101 \
                --dtype bfloat16 
              wait
          ports:
            - name: port-model
              containerPort: 8101

          resources:
            limits:
              nvidia.com/gpu: '1'
            requests:
              nvidia.com/gpu: '1'
          volumeMounts:
            - name: pvc-model-param5b
              mountPath: /platform_storage
            - name: cache
              mountPath: /.cache
            - name: config-volume
              mountPath: /.config
            - name: triton-volume
              mountPath: /.triton
      volumes:
        - name: pvc-model-param5b
          persistentVolumeClaim:
            claimName: pvc-model-param5b
        - name: cache
          emptyDir: {}
        - name: config-volume
          emptyDir: {}
        - name: triton-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: model-param5b
  namespace: vllm-models
spec:
  type: ClusterIP
  selector:
    app: model-param5b
  ports:
    - name: port-model
      port: 8101
      targetPort: port-model
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: model-param5b
  namespace: vllm-models
spec:
  host: param5b.impactsummit.nxtgen.cloud
  to:
    kind: Service
    name: model-param5b
  port:
    targetPort: port-model
  tls:
    termination: edge
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-model-param5b
  namespace: vllm-models
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ocs-storagecluster-ceph-rbd